### ISSUE TITLE
Libs

### ISSUE THREAD

**Issue by gaveer** [nrpieper/wow-misspelled#1]
7x Couldn't open Misspelled\Libs\AceGUI-3.0-39\AceGUI-3.0.xml
7x Couldn't open Misspelled\Libs\AceEvent-3.0-4\AceEvent-3.0.xml
7x Couldn't open Misspelled\Libs\AceLocale-3.0-6\AceLocale-3.0.xml
7x Couldn't open Misspelled\Libs\AceHook-3.0-8\AceHook-3.0.xml
14x Error loading Misspelled\Libs\LibStub\LibStub.lua
14x Couldn't open Misspelled\Libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml
14x Couldn't open Misspelled\Libs\AceAddon-3.0-12\AceAddon-3.0.xml

**Comment by gaveer** [comment]
i think you need to uplode the libs into the github

**Comment by nrpieper** [comment]
Working on releasing an update now
